In [38]:
import numpy as np

In [39]:
# Criando um array

# Arrays são muito interessantes para evitarmos os gastos que são implementados
# pela linguagem python em listas.

In [40]:
# Criando Arrays

lista_inteiros = list(range(1000))

In [41]:
print(lista_inteiros)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [42]:
array_1 = np.array(lista_inteiros.append("uma string"))

In [43]:
print(array_1.dtype)

object


In [44]:
# Quando temos apenas inteiros temos um vetor de inteiros, quando temos apenas uma string
# todo o vetor é do tipo object.

In [45]:
np.array([1, 2, 3]).dtype

dtype('int64')

In [46]:
array_2 = np.array([1, 2, 3, 4, 5.1])

In [47]:
print(array_2.dtype)

float64


In [48]:
array_2

array([1. , 2. , 3. , 4. , 5.1])

In [49]:
# Ditando o tipo de dados do array na criação

array_3 = np.array([1, 2, 3, 4, 5.2], dtype= np.int32)

In [50]:
array_3 # O valor após o ponto é simplesmente ignorado

array([1, 2, 3, 4, 5], dtype=int32)

In [51]:
array_4 = np.array([1, 2, 3, 4.5, 4.10, 1.30], dtype= np.float16)

In [52]:
array_4

array([1. , 2. , 3. , 4.5, 4.1, 1.3], dtype=float16)

In [53]:
# Criando um array numpy multidimensional, partindo de listas aninhadas.

matriz = np.array([range(i, i + 3) for i in [2, 4, 6]], dtype= np.int8)

In [54]:
matriz.dtype

dtype('int8')

In [55]:
# Criando Arrays com as rotinas predefinidas do numpy

vetor_zeros = np.zeros(15, dtype= int)

In [56]:
vetor_zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
vector_ones = np.ones(10, dtype= np.int8)

In [58]:
vector_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [59]:
# Matriz ones

# 3 x 5 = Três linhas e cinco colunas
matriz_ones = np.ones((3, 5), dtype= np.int8)

In [60]:
matriz_ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [61]:
# np.full

# Preeche uma matriz específicada com um valor específicado

matriz_pi = np.full((3, 5), 3.14)

In [62]:
matriz_pi

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [63]:
# Criando sequências numéricas, algo que lembra uma progressão aritmética simples.
# Imprime o intervalo de numeros entre o 0 e o 10 saltando de 2 em dois, muito parecido com o range nativo python.
pares = np.arange(0, 10, 2)

In [64]:
print(pares)

[0 2 4 6 8]


In [65]:
# Criado uma sequência de valores igualmente espaçados entre 0 e 1.


np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [66]:
# Criando uma Matriz 3x3 de valores pseudoaleatórios
# entre 0 e 1
np.random.random((3, 3))

array([[0.34948025, 0.68291804, 0.60040835],
       [0.50121579, 0.20614915, 0.63534317],
       [0.93736201, 0.17696636, 0.97418196]])

In [67]:
# Criando uma matriz de valores de média 0 e desvio de padrão 1

matriz_media_zero = np.random.normal(0, 1, (3, 3))

In [68]:
matriz_media_zero

array([[-0.55129838,  1.35260627, -0.65998988],
       [ 1.61826366, -0.67804635,  0.44788726],
       [-0.83645183,  0.63808055, -0.54968063]])

In [69]:
 range?

In [86]:
# Criando uma matriz com valores entre 0 e 10, [0, 10)

# Dá para gerar Matrizes de inteiros pseudoaleatórios.
np.random.randint(0, 1000, (3, 3))

array([[718,  49, 683],
       [737, 698, 927],
       [731, 719,  57]])

In [90]:
# Criando uma matriz identidade três por três
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [92]:
# Criando um vetor não inicializado de três inteiros.
np.empty(3)


array([1., 1., 1.])

In [93]:
# Os tipos de dados específicos do NumPy.
# Saber isto é importante, pois os nossos vetores são de apenas
# um único tipo de dados.

vetor_1 = np.zeros(10, dtype= 'int16')
vetor_2 = np.zeros(10, dtype= np.int16)

In [94]:
vetor_2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [95]:
array_1 = np.array([1, 2, 3, 4, 5], dtype= 'int8')

In [96]:
print(array_1.dtype)

int8


In [100]:
vetor_bools = np.array([True, False, True], dtype= np.object_)

In [101]:
print(vetor_bools.dtype)


object


In [102]:
# Os Tipos de Dados Específicos do NumPy.