In [4]:
import numpy as np

In [ ]:
# Manipulação de arrays.

In [ ]:
# Atributos de um array NumPy

In [5]:
# Definindo uma seed padrão para os exemplos

rng = np.random.default_rng(seed= 1701) # Seed para reprodução.

In [6]:
# Definindo arrays de exemplo

x1 = rng.integers(10, size= 6) # Array unidimensional
x2 = rng.integers(10, size= (3, 4)) # Array de duas dimensões, linhas e colunas.
x3 = rng.integers(10, size= (3, 4, 5)) # Array tidimensional

In [9]:
# Alguns atributos que cada um dos arrays possui

print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype: ", x3.dtype)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 dtype:  int64


In [10]:
# Indexação
# Acessando elementos do array pelo índice

x1

array([3, 1, 3, 7, 4, 0])

In [11]:
x1[0]

np.int64(3)

In [12]:
x1[2]

np.int64(3)

In [13]:
x1[4]

np.int64(4)

In [14]:
# Acessando elementos apartir do meio do array.

x1[-1]

np.int64(0)

In [15]:
x1[-2]

np.int64(4)

In [16]:
# Acessando os valores de uma matriz multidimensional.

x2

array([[2, 3, 0, 0],
       [6, 9, 4, 3],
       [5, 5, 0, 8]])

In [18]:
# Segunda linha primeiro elemento
x2[1, 0]

np.int64(6)

In [19]:
x2[2, 3]

np.int64(8)

In [22]:
x2[0, -3]

np.int64(3)

In [23]:
# Alterando valores em array NumPy

x2[0, -1] = 10

In [24]:
x2

array([[ 2,  3,  0, 10],
       [ 6,  9,  4,  3],
       [ 5,  5,  0,  8]])

In [25]:
x2[0, -1]

np.int64(10)

In [28]:
# Como os arrays NumPy tem um tipo de dados fixo quando tentarmos adicionar um float a um array
# de inteiros este valor será truncado automáticamente, a parte decimal será trocada.

x1[0] = 3.4

x1

array([3, 1, 3, 7, 4, 0])

In [29]:
# Tipo de dados variável, permite tipos diferentes de dados
# na mesma estrutura.

numeros = [1, 3, 5, 7]
numeros[0] = 10.5

In [30]:
numeros

[10.5, 3, 5, 7]

In [ ]:
# Fatiamento de Array

# x[start: end: step]

# x[ínicio= 0: final= dimensão do array: salto= 1] Comportamento Padrão

In [ ]:
# SUBARRAYS

In [3]:
# Sub arrays unidimensionais.

x1

NameError: name 'x1' is not defined

In [32]:
# Os três primeiros elementos
x1[:3]

array([3, 1, 3])

In [33]:
# Elementos depois do índice três

x1[3:]

array([7, 4, 0])

In [34]:
x1[1: 4]

array([1, 3, 7])

In [7]:
# Cada segundo elemento do array

x1[0: x1.size - 1: 2]

array([9, 0, 8])

In [9]:
# Acessando cada segundo array
x1[:: 2]

array([9, 0, 8])

In [10]:
x1

array([9, 4, 0, 3, 8, 6])

In [11]:
# Acessando cada segundo array, partindo do primeiro item

x1[1::2]

array([4, 3, 6])

In [12]:
# Quando o step é negativo o start e o end são trocados.

x1[::-1] # Agora começamos no último elementos até o primeiro

array([6, 8, 3, 0, 4, 9])

In [13]:
# Saltando de dois em dois do fim para começo

x1[::-2]

array([6, 3, 4])

In [ ]:
# Cada segundo elemento partindo de ordem invertida começando no quatro.

In [ ]:
# Subarrays multidimensionais.


In [14]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [15]:
# x2[linha inicial: linha final, coluna inicial: coluna final]
x2[:2, :3]

# Acessando as primeiras linhas e as duas últimas colunas.

array([[3, 1, 3],
       [4, 0, 2]])

In [29]:
# Acessando três linhas a cada segunda coluna

# x2[linha inicial: linha final: salto da linha, coluna inicial: coluna final: salto coluna]
x2[:3:1, ::2]

array([[3, 3],
       [4, 2],
       [0, 6]])

In [30]:
x2[:3]

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [31]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [32]:
# Todas as linhas e colunas em ordem inversa

x2[::-1, ::-1]

array([[9, 6, 0, 0],
       [3, 2, 0, 4],
       [7, 3, 1, 3]])

In [33]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [35]:
# Acessando colunas completas da matriz

x2[:, 1]

array([1, 0, 0])