In [1]:
import numpy as np

In [ ]:
# Manipulação de arrays.

In [ ]:
# Atributos de um array NumPy

In [2]:
# Definindo uma seed padrão para os exemplos

rng = np.random.default_rng(seed= 1701) # Seed para reprodução.

In [5]:
# Definindo arrays de exemplo

x1 = rng.integers(10, size= 6) # Array unidimensional
x2 = rng.integers(10, size= (3, 4)) # Array de duas dimensões, linhas e colunas.
x3 = rng.integers(10, size= (3, 4, 5)) # Array tidimensional

In [ ]:
# Alguns atributos que cada um dos arrays possui

print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype: ", x3.dtype)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 dtype:  int64


In [ ]:
# Indexação
# Acessando elementos do array pelo índice

x1

array([3, 1, 3, 7, 4, 0])

In [6]:
x1[0]

np.int64(8)

In [7]:
x1[2]

np.int64(7)

In [ ]:
x1[4]

np.int64(4)

In [8]:
# Acessando elementos apartir do meio do array.

x1[-1]

np.int64(2)

In [10]:
x1[-2]

np.int64(3)

In [14]:
# Acessando os valores de uma matriz multidimensional.

x2

array([[1, 2, 9, 3],
       [1, 2, 8, 0],
       [7, 3, 3, 6]])

In [15]:
# Segunda linha primeiro elemento
x2[2, 0]

np.int64(7)

In [16]:
x2[2, 3]

np.int64(6)

In [17]:
x2[0, -3]

np.int64(2)

In [18]:
# Alterando valores em array NumPy

x2[0, -1] = 10

In [19]:
x2

array([[ 1,  2,  9, 10],
       [ 1,  2,  8,  0],
       [ 7,  3,  3,  6]])

In [20]:
x2[0, -1]

np.int64(10)

In [ ]:
# Como os arrays NumPy tem um tipo de dados fixo quando tentarmos adicionar um float a um array
# de inteiros este valor será truncado automáticamente, a parte decimal será trocada.

x1[0] = 3.4

x1

array([3, 1, 3, 7, 4, 0])

In [ ]:
# Tipo de dados variável, permite tipos diferentes de dados
# na mesma estrutura.

numeros = [1, 3, 5, 7]
numeros[0] = 10.5

In [ ]:
numeros

[10.5, 3, 5, 7]

In [ ]:
# Fatiamento de Array

# x[start: end: step]

# x[ínicio= 0: final= dimensão do array: salto= 1] Comportamento Padrão

In [ ]:
# SUBARRAYS

In [ ]:
# Sub arrays unidimensionais.

x1

NameError: name 'x1' is not defined

In [ ]:
# Os três primeiros elementos
x1[:3]

array([3, 1, 3])

In [ ]:
# Elementos depois do índice três

x1[3:]

array([7, 4, 0])

In [ ]:
x1[1: 4]

array([1, 3, 7])

In [ ]:
# Cada segundo elemento do array

x1[0: x1.size - 1: 2]

array([9, 0, 8])

In [ ]:
# Acessando cada segundo array
x1[:: 2]

array([9, 0, 8])

In [ ]:
x1

array([9, 4, 0, 3, 8, 6])

In [ ]:
# Acessando cada segundo array, partindo do primeiro item

x1[1::2]

array([4, 3, 6])

In [ ]:
# Quando o step é negativo o start e o end são trocados.

x1[::-1] # Agora começamos no último elementos até o primeiro

array([6, 8, 3, 0, 4, 9])

In [ ]:
# Saltando de dois em dois do fim para começo

x1[::-2]

array([6, 3, 4])

In [ ]:
# Cada segundo elemento partindo de ordem invertida começando no quatro.

In [ ]:
# Subarrays multidimensionais.


In [ ]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [ ]:
# x2[linha inicial: linha final, coluna inicial: coluna final]
x2[:2, :3]

# Acessando as primeiras linhas e as duas últimas colunas.

array([[3, 1, 3],
       [4, 0, 2]])

In [ ]:
# Acessando três linhas a cada segunda coluna

# x2[linha inicial: linha final: salto da linha, coluna inicial: coluna final: salto coluna]
x2[:3:1, ::2]

array([[3, 3],
       [4, 2],
       [0, 6]])

In [ ]:
x2[:3]

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [ ]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [ ]:
# Todas as linhas e colunas em ordem inversa

x2[::-1, ::-1]

array([[9, 6, 0, 0],
       [3, 2, 0, 4],
       [7, 3, 1, 3]])

In [ ]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [ ]:
# Acessando colunas completas da matriz

x2[:, 1]

array([1, 0, 0])

In [21]:
# Primeira linha do array

x2[0, :]

array([ 1,  2,  9, 10])

In [23]:
# Acessando a primeira linha do array de uma forma mais compacta
x2[0]

array([ 1,  2,  9, 10])

In [23]:
# SubArrays como Views

# Diferentemente Das listas python os subarrays construidos com NumPy, não são cópias exatas,
# mas sim Views, que quando alteradas alteram também as originais.

In [29]:
x2

array([[100,   2,   9,  10],
       [  1,   2,   8,   0],
       [  7,   3,   3,   6]])

In [25]:
x2_sub = x2[:2, :2]

In [30]:
x2_sub

array([[100,   2],
       [  1,   2]])

In [32]:
x2_sub[0, 0] = 800

In [33]:
x2_sub

array([[800,   2],
       [  1,   2]])

In [34]:
x2

array([[800,   2,   9,  10],
       [  1,   2,   8,   0],
       [  7,   3,   3,   6]])

In [35]:
# Criando cópias reais, utilizando o método copy.

x2_sub_copy = x2[:2, :2].copy()

In [36]:
print(x2_sub_copy)

[[800   2]
 [  1   2]]


In [37]:
x2_sub_copy[0, 0] = 500

In [38]:
x2_sub_copy

array([[500,   2],
       [  1,   2]])

In [39]:
x2

array([[800,   2,   9,  10],
       [  1,   2,   8,   0],
       [  7,   3,   3,   6]])